### ISSUE TITLE
LNK2001 Error in DLLMain.obj when compiling

### ISSUE THREAD

**Issue by kool-thing** [afulsamet/KateBot-Remastered#2]
I've tried compiling on both Windows 7 and Windows 10.
I have a feeling the error may be due to the httplib.h I am using. To include it I simply put it into the include folder of the MSVC Toolkit version I'm using. Not sure if that is correct. The link error may not be related to the httplib.h header at all.
![zzz](https://user-images.githubusercontent.com/63286819/78649085-f2a5e600-788a-11ea-9640-6ec475411ee2.PNG)
Any help would be appreciated. Thank you.

**Comment by afulsamet** [comment]
I wanted external menu to have an HTTP Web page and i used [cpp-httplib](https://github.com/yhirose/cpp-httplib) but i thought it would take a long time and gave up. Actually, "httplib.h" is unnecessary now and do not use it and try

**Comment by kool-thing** [comment]
Oh okay, so httplib.h is not needed.
Even when I remove it though, I still have the LNK2001 Error.
So it appears something is wrong in a header inside of main.h
Particularly the Colors struct

**Comment by afulsamet** [comment]
Check this commit[#Fixed someshits](https://github.com/afulsamet/KateBot-Remastered/commit/1f2fa59389f267e26f8a1b708577ce42010f16cf) will solve your mistake.

**Comment by kool-thing** [comment]
I could only compile as release, and still I get a Link Warning.
With the dll. though, it crashes after a few seconds and asks me to if i want to debug

**Comment by kool-thing** [comment]
Completely standard injection doesn't crash.
All features appear to work now! Thanks
