### ISSUE TITLE
Built Fail From VS2019

### ISSUE THREAD

**Issue by alexEsmartBoy** [afulsamet/KateBot-Remastered#3]
Hi Afulsamet,

Thanks for your the kindest contribution.

While attempting to compile from VS2019. I have faced error code. LNK2001 & LNK1120

![image](https://user-images.githubusercontent.com/63332067/78744145-66cbb100-7993-11ea-9884-71db0a567a81.png)

This error is similar to kool-thing post, however due to my limit. I could not understand what has been done in the previous post to resolve.

**Comment by kool-thing** [comment]
Compile as release should fix it

**Comment by alexEsmartBoy** [comment]
Thanks for prompt reply kool-thing.

I am able to inject. But when i test i could not see any glow happening.

**Comment by kool-thing** [comment]
Could be your config settings. Not sure what else.

**Comment by alexEsmartBoy** [comment]
Configuration wise i am using the one Afulsamet provided.

**Comment by kool-thing** [comment]
Well the one he provided has glow disabled. Do you see any other features activated in your game?

**Comment by alexEsmartBoy** [comment]
My injected console

![image](https://user-images.githubusercontent.com/63332067/78745612-4a317800-7997-11ea-8c57-d5aec88f6db0.png)

![image](https://user-images.githubusercontent.com/63332067/78745732-91b80400-7997-11ea-9c89-663980301700.png)

**Comment by alexEsmartBoy** [comment]
I will say only active feature will be bunny hop

**Comment by alexEsmartBoy** [comment]
Mind share the injector you're using? I am currently using xtreme

**Comment by kool-thing** [comment]
Turn off stream mode. I also use extreme.

**Comment by alexEsmartBoy** [comment]
Gotcha! Wanna play together? Thanks for the help

**Comment by alexEsmartBoy** [comment]
Leave ur steamID i add you.

**Comment by kool-thing** [comment]
https://steamcommunity.com/id/ks346vcg367waawtg3/
We can play sometime, but not now as I am doing homework.

**Comment by alexEsmartBoy** [comment]
Added, :) See you there.
