### ISSUE TITLE
Hitsounds make the game crash

### ISSUE THREAD

**Issue by lenixxq** [afulsamet/KateBot-Remastered#4]
It crashes the game If I enable hitsounds and shoot someone. The instant I shoot someone anywhere in the body, The game crashes. Also, I liked everything you did to katebot but if you remember the vanilla version, It has a color scheme from Green to Red for ESP Only which signifies health of enemy. By any chance can I achieve this?

**Comment by afulsamet** [comment]
I don't know exactly where game has crashed. I tested `ofs->m_dwClientCMD` on IDA and it's still have a right pattern. You can debug the game and in this way you can understand exactly where it crashed.

Also, health-based ESP already exists, but it is not made up of if statements.
[Take a look here, GlowESP#L66](https://github.com/afulsamet/KateBot-Remastered/blob/master/KateBot/cheats/GlowESP.h#L66)

**Comment by lenixxq** [comment]
> I don't know exactly where game has crashed. I tested `ofs->m_dwClientCMD` on IDA and it's still have a right pattern. You can debug the game and in this way you can understand exactly where it crashed.
> 
> Also, health-based ESP already exists, but it is not made up of if statements.
> [Take a look here, GlowESP#L66](https://github.com/afulsamet/KateBot-Remastered/blob/master/KateBot/cheats/GlowESP.h#L66)

Okay yeah I see it exists there but How do I enable it? I mean when I turn on ESP and the chams are off, the enemies are always red. Besides, the rank revealer is CMD based?? I don't understand what that means cause when I play ranked, it is not showing up their ranks in the Scoreboard. Do I need to manually enter something in-game console for that or is it broke?

**Comment by afulsamet** [comment]
Please take a look at `Config.ini`, you will see everything there.
```ini
[GlowESP]
NoFlicker.Enable = true
EnemiesOnly.Enable = true
OnlyVisible.Enable = false
HealthBased.Enable = false
Color.Red = 255
Color.Green = 0
Color.Blue = 0
Color.Alpha = 70
```

You must use `HealthBased.Enable` feature as `true`.
```ini
HealthBased.Enable = true
```

For the rank revealer, open in-game console and press HOME key and see the result (valid only for competitive matches/demos.). Ranks and wins will not be visible except for competitive matches/demos.

In in-game console, rank results will look like this.
```
Rank Revealer

Terrorists
==============================
afulsamet - [Gold Nova II] - 1387 wins
...

Counter-Terrorists
==============================
lenixxq - [Global Elite] - 2 wins
...
```

**Comment by lenixxq** [comment]
> Please take a look at `Config.ini`, you will see everything there.
> 
> ```ini
> [GlowESP]
> NoFlicker.Enable = true
> EnemiesOnly.Enable = true
> OnlyVisible.Enable = false
> HealthBased.Enable = false
> Color.Red = 255
> Color.Green = 0
> Color.Blue = 0
> Color.Alpha = 70
> ```
> 
> You must use `HealthBased.Enable` feature as `true`.
> 
> ```ini
> HealthBased.Enable = true
> ```
> 
> For the rank revealer, open in-game console and press HOME key and see the result (valid only for competitive matches/demos.). Ranks and wins will not be visible except for competitive matches/demos.
> 
> In in-game console, rank results will look like this.
> 
> ```
> Rank Revealer
> 
> Terrorists
> ==============================
> afulsamet - [Gold Nova II] - 1387 wins
> ...
> 
> Counter-Terrorists
> ==============================
> lenixxq - [Global Elite] - 2 wins
> ...
> ```

So pressing home also crashes the game when I am in competitive. Any fix?

**Comment by afulsamet** [comment]
All features work for me and my testers, problem may be related to you. 

As I said 
> You can debug the game and in this way you can understand exactly where it crashed.

**Comment by lenixxq** [comment]
> > You can debug the game and in this way you can understand exactly where it crashed.

I looked up but katebot changed and they say offset dumpers don't work if you change offsets in config cause it is self updating. Can you suggest something? About how do I debug the game? Attach it to the game via Visual studio?
