### ISSUE TITLE
External Error

### ISSUE THREAD

**Issue by RLDoN3** [afulsamet/KateBot-Remastered#5]
![Capturar](https://user-images.githubusercontent.com/44685053/79081806-01f7ba00-7cf7-11ea-80b7-7b427f8193ed.PNG)

**Comment by afulsamet** [comment]
Clone [Fixed someshits](https://github.com/afulsamet/KateBot-Remastered/commit/1f2fa59389f267e26f8a1b708577ce42010f16cf) commit and build as release.
